version: '3.8'

services:
  rust_app:
    build: .
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
    depends_on:
      - db
    environment:
      DATABASE_URL: ${DATABASE_URL}
    restart: always
    networks:
      - rust_todo_api_network

  db:
    image: postgres:15
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_USERNAME}
      POSTGRES_DB: ${DB_USERNAME}
    ports:
      - ${DB_PORT_MAPPED}:${DB_PORT}
    volumes:
      - ./dockerfiles/postgres_data:/var/lib/postgresql/data
    restart: always
    networks:
        - rust_todo_api_network
  
  pgadmin:
      image: dpage/pgadmin4
      environment:
        PGADMIN_DEFAULT_EMAIL: admin@example.com
        PGADMIN_DEFAULT_PASSWORD: admin
      ports:
        - "5050:80"
      depends_on:
        - db
      restart: always
      networks:
        - rust_todo_api_network

volumes:
  postgres_data: ~

networks:
    rust_todo_api_network:
        driver: bridge
